[tool.poetry]
name = "battlesnake"
version = "1.0.0"
description = "A simple Battlesnake written in Python"
authors = ["Nils Wrenger <nils@wrenger.net>"]

[tool.poetry.dependencies]
python = "^3.8"
cherrypy = "^18.6"
pygame = "^1.9.6"
numpy = "^1.19.2"
requests = "*"
pathfinding = "*"
